baseURL = 'https://gaber-foundation.github.io/'
title = 'مؤسسة جابر للبحث والتحقيق'
theme = 'newsroom'
defaultContentLanguage = 'ar'

# أخبر هوجو أن مجلد _partials هو مكان الـ partials الرسمي
[[module.mounts]]
    source = 'layouts'
    target = 'layouts'

[[module.mounts]]
    source = 'layouts/_partials'
    target = 'layouts/partials'

[languages.ar]
    languageName = 'العربية'
    languagedirection = 'rtl'
    contentDir = 'content'

[params]
    description = "مؤسسة صحفية استقصائية - كشف الحقائق ونصرة المظلوم"
