baseURL = 'https://gaber-foundation.github.io/'
title = 'مؤسسة جابر للبحث والتحقيق'
theme = 'newsroom'
defaultContentLanguage = 'ar'

[languages.ar]
    languageName = 'العربية'
    languagedirection = 'rtl'
    title = 'مؤسسة جابر للبحث والتحقيق'
    contentDir = 'content'
