name = "فاطمة سعيد جابر"
license = "MIT"
licenselink = "https://github.com/onweru/newsroom/blob/master/LICENSE.md"
description = "A simple open source theme for publishing multi-purpose content"
homepage = "https://gaber-foundation.github.io"
demosite = "https://rooms.netlify.app/"
tags = [
  "blog",
  "simple",
  "dark",
  "minimalist",
  "fast",
  "disqus",
  "syntax highlighting",
]
features = [
  "blog",
  "simple",
  "dark",
  "minimalist",
  "fast",
  "disqus",
  "syntax highlighting",
]
min_version = "0.146.0"

[author]
name = "فاطمة سعيد جابر"
homepage = "https://gaber-foundation.github.io"
