# الإعدادات الأساسية
baseURL = "https://gaber-foundation.github.io/"
title = "مؤسسة جابر للبحث والتحقيق"
theme = ["github.com/onweru/newsroom"]
author = "فاطمة سعيد جابر"
defaultContentLanguage = 'ar'

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[params]
    description = "مؤسسة صحفية استقصائية - كشف الحقائق ونصرة المظلوم"


[languages.ar]
    contentDir = 'content'
    languageName = 'العربية'
    weight = 1
    languagedirection = 'rtl'


[permalinks]
pages = ':contentbasename/'

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"
