baseURL = "https://gaber-foundation.github.io/"
title = "مؤسسة جابر للبحث والتحقيق"
defaultContentLanguage = 'ar'

# الطريقة الصحيحة لاستدعاء القالب كـ Module

theme = [
  "github.com/Gaber-Foundation/gaber-foundation.github.io",
] # edit this if you'ld rather use a fork of this repo
# theme = "newsroom"
author = "Gaber-Foundation"
[params]
    mainSections = ["post", "posts"]
    blogDir = "posts"
    description = "مؤسسة صحفية استقصائية - كشف الحقائق ونصرة المظلوم"

[languages.ar]
    contentDir = 'content'
    label = 'العربية'       # بدل languageName (عشان الـ WARN يختفي)
    weight = 1
    direction = 'rtl'   # بدل languageDirection (عشان الـ WARN يختفي)
