# الإعدادات الأساسية
baseURL = "https://gaber-foundation.github.io/"
title = "مؤسسة جابر للبحث والتحقيق"
theme = ["github.com/onweru/newsroom"]
author = "فاطمة سعيد جابر"
defaultContentLanguage = 'ar'

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[params]
    description = "مؤسسة صحفية استقصائية - كشف الحقائق ونصرة المظلوم"
    mainSections = ["post", "posts"]
    blogDir = "posts"

[languages.ar]
    contentDir = 'content'
    languageName = 'العربية'
    weight = 1
    languagedirection = 'rtl'

# السحر هنا: ربط المجلدات اللي بتبدأ بـ (_) بالمسارات اللي Hugo بيفهمها
[[module.mounts]]
    source = 'layouts'
    target = 'layouts'

[[module.mounts]]
    source = 'layouts/_partials'
    target = 'layouts/partials'

[[module.mounts]]
    source = 'layouts/_shortcodes'
    target = 'layouts/shortcodes'

[[module.mounts]]
    source = 'assets'
    target = 'assets'
